### ISSUE TITLE
Suivi : élus pouvant présenter un candidat

### ISSUE THREAD

**Issue by ronnix** [ronnix/parrainage#74]
[Élu·e·s pouvant présenter un candidat](https://fr.wikipedia.org/wiki/Pr%C3%A9sentation_des_candidats_%C3%A0_l%27%C3%A9lection_pr%C3%A9sidentielle_fran%C3%A7aise#%C3%89lus_pouvant_pr%C3%A9senter_un_candidat) (_wikipedia.fr_) :

- [x] les député·e·s ([#8](https://github.com/ronnix/parrainage/issues/8), [#16](https://github.com/ronnix/parrainage/pull/16), [#17](https://github.com/ronnix/parrainage/pull/17), [#18](https://github.com/ronnix/parrainage/pull/18))
- [x] les sénateur·ice·s ([#6](https://github.com/ronnix/parrainage/pull/6))
- [x] les ressortissant·e·s français·es membres du Parlement européen élu·e·s en France ([#26](https://github.com/ronnix/parrainage/issues/26), [#28](https://github.com/ronnix/parrainage/pull/28))
- les membres :
    - [x] des conseils régionaux ([#6](https://github.com/ronnix/parrainage/pull/6))
    - [x] des conseils départementaux ([#6](https://github.com/ronnix/parrainage/pull/6))
    - [x] de l’Assemblée de Corse ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] du conseil de la métropole de Lyon ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] de l’Assemblée de Guyane ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] de l’Assemblée de Martinique ([#66](https://github.com/ronnix/parrainage/pull/66))
    - des conseils territoriaux :
        - [x] de Saint-Barthélemy ([#66](https://github.com/ronnix/parrainage/pull/66))
        - [x] de Saint-Martin ([#66](https://github.com/ronnix/parrainage/pull/66))
        - [x] de Saint-Pierre-et-Miquelon ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] de l’assemblée de la Polynésie française ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] des assemblées de province de la Nouvelle-Calédonie ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] de l’assemblée territoriale des îles Wallis et Futuna ([#66](https://github.com/ronnix/parrainage/pull/66))
    - [x] du Conseil de Paris ([#29](https://github.com/ronnix/parrainage/issues/29), [#67](https://github.com/ronnix/parrainage/pull/67))
- [x] les maires
- [x] les maires délégués des communes déléguées et des communes associées ([#70](https://github.com/ronnix/parrainage/pull/70))
- [ ] les maires des arrondissements de Paris, de Lyon et de Marseille ([#44](https://github.com/ronnix/parrainage/issues/44))
- [ ] les conseiller·e·s à l’Assemblée des Français de l’étranger
- [x] les président·es des organes délibérants des métropoles, communautés urbaines, des communautés d’agglomération et des communautés de communes ([#25](https://github.com/ronnix/parrainage/issues/25), [#27](https://github.com/ronnix/parrainage/pull/27))
- [ ] le ou la président·e de la Polynésie française
- [ ] le ou la président·e du gouvernement de la Nouvelle-Calédonie
